import Head from "next/head";
import { Navbar, NFTCard } from "../components/componentsIndex";


// INternal Imports
import Styles from "../styles/Home.module.css";
import {alien, frankenstein, bat} from "../img";
const Home = () => {

  const nftDemoData = [
    {
      imageURL: alien,
      name: "Alien",
      price: "0.01",
      tokenId: 1
    }, {
      imageURL: frankenstein,
      name: "Frankenstein",
      price: "0.04",
      tokenId: 2
    },
    {
      imageURL: bat,
      name: "Bat",
      price: "0.03",
      tokenId: 3
    }
  ]
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={Styles.home_container} >
        <p className={Styles.home_cta}>Purchase Your Favourite Non-Fungible Token</p>
      </div>
      <div className={Styles.nftCards_container}>
        {nftDemoData.map((nftData, index) => {
          return (
            <NFTCard key={index + 1} nftData = {nftData} />
          )
        })}
      </div> 
    </div>
  )
}

export default Home